export const rappers = [
  "Jul",
  "PNL",
  "Ninho",
  "Damso",
  "Nekfeu",
  "Niska",
  "Maitre Gims",
  "Orelsan",
  "Kaaris",
  "Kery James",
  "Lomepal",
  "MC Solaar",
  "Gradur",
  "Diam s",
  "SCH",
  "IAM",
  "Oxmo Puccino",
  "Jazzy Bazz",
  "Vald",
  "Keny Arkana",
  "Roméo Elvis",
  "Rohff",
  "Seth Gueko"
];

export const chansonFr = [
  "Johnny Hallyday",
  "Charles Aznavour",
  "Édith Piaf",
  "Serge Gainsbourg",
  "Georges Brassens",
  "Renaud",
  "Francis Cabrel",
  "Alain Souchon",
  "Jacques Brel",
  "Barbara",
  "Joe Dassin",
  "Céline Dion",
  "Mylene Farmer",
  "Claude François",
  "Jacques Dutronc",
  "Françoise Hardy",
  "Michel Berger",
  "france Gall",
  "Sheila",
  "Véronique Sanson",
  "Dalida",
  "Léo Ferré",
  "Angèle",
  "Sylvie Vartan"
];
